### ISSUE TITLE
Rearrange Bio Tiles on the About Page

### ISSUE THREAD

**Issue by ejj28** [FRC6854/FRC6854.github.io#2]
The Bio Tiles on the About Page are kinda scattered about, they need to be rearranged

**Comment by Tntcommando1** [comment]
We have resolved this issue, thank you for your input!

**Comment by ejj28** [comment]
They're still kinda scattered..

**Comment by ejj28** [comment]
@Tntcommando1 On my computer (1280x800 resolution), at normal zoom levels they're still scattered, upon zooming out they become less scattered but still not perfect, I think this could be resolved by making all the bio cards equal height

**Comment by ejj28** [comment]
Further investigation has revealed that differing card heights is indeed the problem, I'll try to fix this by adding NewLines to the bottom of shorter cards

**Comment by ejj28** [comment]
After further investigations it looks like because the text will wrap differently at different screen resolutions and zoom levels, the NewLine method won't work. I'm currently looking at alternative methods.
