### ISSUE TITLE
Picture on about page looks upside down in a mobile browser

### ISSUE THREAD

**Issue by JasonBrave** [FRC6854/FRC6854.github.io#6]
Picture on about page looks upside down in a mobile phone browser
 desktop browser:
<img width="955" alt="desktop" src="https://user-images.githubusercontent.com/40355221/46446882-cd439380-c74c-11e8-87e8-1bc86a207095.PNG">
mobile phone browser:
![mobile](https://user-images.githubusercontent.com/40355221/46446896-d9c7ec00-c74c-11e8-9ade-ca7ea79672a2.PNG)

**Comment by Tntcommando1** [comment]
We are aware of this issue. We think this is due to the mobile browser.

**Comment by JasonBrave** [comment]
I think this cause the problem:
<img class="img-responsive" src="images/teamphotowindsor.jpg" alt="about" style="transform:rotate(180deg);">
<img width="960" alt="upsidedown" src="https://user-images.githubusercontent.com/40355221/46447171-64f5b180-c74e-11e8-87ed-8f87f2cd7e7e.PNG">

**Comment by JasonBrave** [comment]
I think this cause the problem
<code><img class="img-responsive" src="images/teamphotowindsor.jpg" alt="about" style="transform:rotate(180deg);"></code>
<img width="960" alt="upsidedown" src="https://user-images.githubusercontent.com/40355221/46447247-b3a34b80-c74e-11e8-8338-02f51d050d0e.PNG">

**Comment by JasonBrave** [comment]
I think this cause the problem
<textarea readonly><img class="img-responsive" src="images/teamphotowindsor.jpg" alt="about" style="transform:rotate(180deg);"></textarea>
<img width="960" alt="upsidedown" src="https://user-images.githubusercontent.com/40355221/46447302-f8c77d80-c74e-11e8-81de-c21e5ce94c3c.PNG">

**Comment by Tntcommando1** [comment]
Issue has been resolved in latest patch.
