### ISSUE TITLE
'Under Construction' Message isn't formatted for responsive design

### ISSUE THREAD

**Issue by ejj28** [FRC6854/FRC6854.github.io#7]
## iPhone X:
![under-construction_iphone-x_portriat](https://user-images.githubusercontent.com/11950233/46573237-4404aa80-c960-11e8-8e1b-af754dffdba2.png)

## iPhone 6(s), 7, 8
![under-construction_iphone-6 7 8_portriat](https://user-images.githubusercontent.com/11950233/46573286-208e2f80-c961-11e8-9b0f-04e32194a64f.png)

## iPhone 6(s) Plus, 7 Plus, 8 Plus
![under-construction_iphone-6plus 7plus 8plus_portriat](https://user-images.githubusercontent.com/11950233/46573273-f6d50880-c960-11e8-9f2f-f227f2cbfd3a.png)

## Samsung Galaxy S9, S9+
![under-construction_galaxy-s9 s9 _portriat](https://user-images.githubusercontent.com/11950233/46573316-6f3bc980-c961-11e8-9e60-58186b3819c2.png)

**Comment by JasonBrave** [comment]
how about just add a picture:
<img width="497" alt="uc" src="https://user-images.githubusercontent.com/40355221/47125972-42868c80-d254-11e8-91ad-eb7d1ca23878.PNG">

**Comment by Tntcommando1** [comment]
The issue has been resolved be removing the icons.
