### ISSUE TITLE
Instagram link on https://frc6854.github.io/index.html can't show up

### ISSUE THREAD

**Issue by JasonBrave** [FRC6854/FRC6854.github.io#8]
<img width="504" alt="no instagram" src="https://user-images.githubusercontent.com/40355221/50388399-41a22900-06e3-11e9-85c4-baa221cacf97.PNG">

**Comment by JasonBrave** [comment]
I think it's caused by this [commit](https://github.com/FRC6854/FRC6854.github.io/commit/a9b679d08a6853b9c51cad7e357563e14f7819d1)

**Comment by minjeff257** [comment]
Should be fixed now

**Comment by JasonBrave** [comment]
open in a new tap should apply on all pages, not only at index.html
